src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    public const PUBLISHED = 1;
    public const DRAFT = 0;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $content;



    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_published = true;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="posts")
     * @Assert\Valid
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }


    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(?bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function setIsDraft()
    {
        $this->is_published = self::DRAFT;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTime('now'));
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }


}

src/Controller/Main/BaseController.php
<?php


namespace App\Controller\Main;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BaseController extends AbstractController
{
    public function renderDefault(){
        return [
            'title' => 'Сайт Symfony Learning'
        ];
    }
}

src/Controller/Main/HomeController.php
<?php


namespace App\Controller\Main;

use App\Entity\Category;
use App\Repository\CategoryRepositoryInterface;
use App\Repository\PostRepositoryInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends BaseController
{
    /**
     * @var PostRepositoryInterface
     */
    private $postRepository;
    /**
     * @var CategoryRepositoryInterface
     */
    private $categoryRepository;

    /**
     * HomeController constructor.
     * @param PostRepositoryInterface $postRepository
     * @param CategoryRepositoryInterface $categoryRepository
     */
    public function __construct(PostRepositoryInterface $postRepository, CategoryRepositoryInterface $categoryRepository)
    {
        $this->postRepository = $postRepository;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * @Route("/", name="home")
     * @return Response
     */
    public function indexAction(){
        $forRender = $this->renderDefault();
        $forRender['posts'] = $this->postRepository->getAll();
        return $this->render('main/index.html.twig', $forRender);
    }

    /**
     * @Route("/filter/categories", name="filter_categories")
     * @return Response
     */
    public function categoryFilter(): Response
    {
        $forRender = $this->renderDefault();
        $forRender['categories'] = $this->categoryRepository->findBy(['is_published' => true], ['updated_at' => 'ASC']);
        $forRender['title'] = 'Фильтр категорий';
        return $this->render('main/filter/index.html.twig', $forRender);
    }
}

templates/main/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
    <div class="container-fluid mt-3 mb-3">
        <div class="row no-gutters">
            <div class="col-12 post-container">
                <div class="row no-gutters">
                    {% for post in posts %}
                        <div class="col-4 p-2">
                            <div class="card text-center">
                                {% if post.img is not null %}
                                    <img class="card-img-top" src="{{ asset('uploads/post/') }}{{ post.img }}" alt="{{ post.title }}">
                                {% else %}
                                    <img class="card-img-top" src="{{ asset('uploads/post/no_image.jpg') }}" alt="{{ post.title }}">
                                {% endif %}
                                <div class="card-body">
                                    {% for category in post.categories %}
                                        {% if category.isPublished %}
                                            <h6 class="text-muted">{{ category.title }}</h6>
                                        {% endif %}
                                    {% endfor %}
                                    <h5 class="card-title">{{ post.title }}</h5>
                                    <p class="card-text">{{ post.content }}</p>
                                    <a href="#" class="btn btn-primary">Читать больше</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>



{% endblock %}